Skipping some example test
due to strange bug with sorting. In Python3 TestSuite() as a result
returns 'str' instead of touple which means later it's impossible to
sort results.....

".tox/py36/lib/python3.6/site-packages/_pytest/python.py:336: in collect
    l.sort(key=lambda item: item.reportinfo()[:2])
    TypeError: '<' not supported between instances of 'str' and 'tuple'"

Might be related to

https://docs.python.org/3/library/unittest.html#unittest.TestSuite.__iter__

See:
https://github.com/mayn/packerlicious/pull/35